---
name: "gradle_build"
description: "Builds a gradle-based module"
inputs:
  skip_test:
    description: "Skip test execution (true|false)"
    required: false
    default: "false"
  version:
    description: "Version for the gradle artifact, defaults to the value read from the project"
    required: false
runs:
  using: "composite"
  steps:
    - id: build
      shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        SKIP_TEST: ${{ inputs.skip_test }}
        VERSION: ${{ inputs.version }}
