---
name: "gradle_build"
description: "Builds a gradle-based module"
inputs:
  docker_registry:
    description: "The registry to persist Docker images"
    required: true
  gpr_user:
    description: "Name of a user with read access to packages, required to get dependencies"
    required: true
  gpr_key:
    description: "Personal Access Token of the gpr_user with read access to packages, required to get dependencies"
    required: true
  helm_registry:
    description: "The registry to persist Helm charts"
    required: true
  kind:
    description: "Whether this build test or test and publish (test|publish)"
    required: "true"
  skip_test:
    description: "Skip test execution (true|false)"
    required: false
    default: "false"
  version:
    description: "Version for the gradle artifact, defaults to the value read from the project"
    required: false
outputs:
  chart_name:
    description: "The name of the published chart, if any"
    value: ${{ steps.build.outputs.chart_name }}
  chart_version:
    description: "The version of the published chart, if any"
    value: ${{ steps.build.outputs.chart_version }}
runs:
  using: "composite"
  steps:
    - id: build
      shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        DOCKER_REGISTRY: ${{ inputs.docker_registry }}
        GITHUB_TOKEN: ${{ github.token  }}
        GPR_USER: ${{ inputs.gpr_user }}
        GPR_KEY:  ${{ inputs.gpr_key }}
        HELM_REGISTRY: ${{ inputs.helm_registry }}
        KIND: ${{ inputs.kind }}
        SKIP_TEST: ${{ inputs.skip_test }}
        VERSION: ${{ inputs.version }}
